//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenariosConfiguration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScenariosConfiguration.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADF CSV file.
        /// </summary>
        public static string ADFCSVfileLabel {
            get {
                return ResourceManager.GetString("ADFCSVfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADF CSV input.
        /// </summary>
        public static string ADFCSVinputLabel {
            get {
                return ResourceManager.GetString("ADFCSVinputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADF CSV to Excel.
        /// </summary>
        public static string ADFCSVtoExcelTitle {
            get {
                return ResourceManager.GetString("ADFCSVtoExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area name.
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion of CSV file was not possible!.
        /// </summary>
        public static string ConversionNotPossibleMessage {
            get {
                return ResourceManager.GetString("ConversionNotPossibleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV error.
        /// </summary>
        public static string ConversionNotPossibleTitle {
            get {
                return ResourceManager.GetString("ConversionNotPossibleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion of CSV file to Excel &apos;{0}&apos; is completed!.
        /// </summary>
        public static string CSVConversionMessage {
            get {
                return ResourceManager.GetString("CSVConversionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADF CSV conversion.
        /// </summary>
        public static string CSVConversionTitle {
            get {
                return ResourceManager.GetString("CSVConversionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CSV file defined does not exists!.
        /// </summary>
        public static string CSVFileDoesNotExistMessage {
            get {
                return ResourceManager.GetString("CSVFileDoesNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file error.
        /// </summary>
        public static string CSVFileDoesNotExistTitle {
            get {
                return ResourceManager.GetString("CSVFileDoesNotExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV separator.
        /// </summary>
        public static string CSVSeparatorLabel {
            get {
                return ResourceManager.GetString("CSVSeparatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DataColumnHeader {
            get {
                return ResourceManager.GetString("DataColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateColumnHeader {
            get {
                return ResourceManager.GetString("DateColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format.
        /// </summary>
        public static string DateFormatLabel {
            get {
                return ResourceManager.GetString("DateFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder ....
        /// </summary>
        public static string DestinationFolderButton {
            get {
                return ResourceManager.GetString("DestinationFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder.
        /// </summary>
        public static string DestinationFolderLabel {
            get {
                return ResourceManager.GetString("DestinationFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Area.
        /// </summary>
        public static string EditArea {
            get {
                return ResourceManager.GetString("EditArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Probe.
        /// </summary>
        public static string EditProbe {
            get {
                return ResourceManager.GetString("EditProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Unit.
        /// </summary>
        public static string EditUnit {
            get {
                return ResourceManager.GetString("EditUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel output.
        /// </summary>
        public static string ExcelOutputLabel {
            get {
                return ResourceManager.GetString("ExcelOutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a file with the same name &apos;{0}&apos;. Do you want to replace the existent file?.
        /// </summary>
        public static string FileWithNameExistsMessage {
            get {
                return ResourceManager.GetString("FileWithNameExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exists.
        /// </summary>
        public static string FileWithNameExistsTitle {
            get {
                return ResourceManager.GetString("FileWithNameExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination folder is not defined!.
        /// </summary>
        public static string FolderDoesNotExistMessage {
            get {
                return ResourceManager.GetString("FolderDoesNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination error.
        /// </summary>
        public static string FolderDoesNotExistTitle {
            get {
                return ResourceManager.GetString("FolderDoesNotExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string IndexColumnHeader {
            get {
                return ResourceManager.GetString("IndexColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe.
        /// </summary>
        public static string Probe {
            get {
                return ResourceManager.GetString("Probe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe.
        /// </summary>
        public static string ProbeColumnHeader {
            get {
                return ResourceManager.GetString("ProbeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe name.
        /// </summary>
        public static string ProbeName {
            get {
                return ResourceManager.GetString("ProbeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probes.
        /// </summary>
        public static string Probes {
            get {
                return ResourceManager.GetString("Probes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string ReadingColumnHeader {
            get {
                return ResourceManager.GetString("ReadingColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CSV ....
        /// </summary>
        public static string SelectCSVButtonText {
            get {
                return ResourceManager.GetString("SelectCSVButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the destination folder.
        /// </summary>
        public static string SelectDestinationFolder {
            get {
                return ResourceManager.GetString("SelectDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TimeColumnHeader {
            get {
                return ResourceManager.GetString("TimeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time format.
        /// </summary>
        public static string TimeFormatLabel {
            get {
                return ResourceManager.GetString("TimeFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string UnitsColumnHeader {
            get {
                return ResourceManager.GetString("UnitsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string ZoneColumnHeader {
            get {
                return ResourceManager.GetString("ZoneColumnHeader", resourceCulture);
            }
        }
    }
}
